apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd-image-updater-system
data:
  registries.conf: |
    registries:
    - name: ghcr
      prefix: ghcr.io
      api_url: https://ghcr.io
      cred_type: basic
      username: $ghcr-creds:username
      password: $ghcr-creds:password

  git.creds: |
    https://github.com:
      username: $gitops-repo-creds:username
      password: $gitops-repo-creds:password

  resource.update.method: git
  resource.git.write: "true"
