apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd-image-updater-system
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater-controller
data:
  log.level: debug


  git.creds: |
    https://github.com:
      username: $gitops-repo-creds:username
      password: $gitops-repo-creds:password


  registries.conf: |
    registries:
    - name: ghcr
      api_url: https://ghcr.io
      prefix: ghcr.io
      default: true

  resource.git.write: "true"
  resource.update.method: git
